In [61]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('survey_results_public.csv')
df.head()

Respondent                                         MainBranch Hobbyist  \
0           1                     I am a developer by profession      Yes   
1           2                     I am a developer by profession       No   
2           3                        I code primarily as a hobby      Yes   
3           4                     I am a developer by profession      Yes   
4           5  I used to be a developer by profession, but no...      Yes   

    Age Age1stCode CompFreq  CompTotal  ConvertedComp             Country  \
0   NaN         13  Monthly        NaN            NaN             Germany   
1   NaN         19      NaN        NaN            NaN      United Kingdom   
2   NaN         15      NaN        NaN            NaN  Russian Federation   
3  25.0         18      NaN        NaN            NaN             Albania   
4  31.0         16      NaN        NaN            NaN       United States   

     CurrencyDesc  ...                  SurveyEase           SurveyLength  \
0   European Euro  ...  Neither easy nor difficult  Appropriate in length   
1  Pound sterling  ...                         NaN                    NaN   
2             NaN  ...  Neither easy nor difficult  Appropriate in length   
3    Albanian lek  ...                         NaN                    NaN   
4             NaN  ...                        Easy              Too short   

  Trans                                     UndergradMajor  \
0    No  Computer science, computer engineering, or sof...   
1   NaN  Computer science, computer engineering, or sof...   
2   NaN                                                NaN   
3    No  Computer science, computer engineering, or sof...   
4    No  Computer science, computer engineering, or sof...   

  WebframeDesireNextYear    WebframeWorkedWith  \
0           ASP.NET Core  ASP.NET;ASP.NET Core   
1                    NaN                   NaN   
2                    NaN                   NaN   
3                    NaN                   NaN   
4   Django;Ruby on Rails         Ruby on Rails   

                              WelcomeChange WorkWeekHrs YearsCode YearsCodePro  
0   Just as welcome now as I felt last year        50.0        36           27  
1  Somewhat more welcome now than last year         NaN         7            4  
2  Somewhat more welcome now than last year         NaN         4          NaN  
3  Somewhat less welcome now than last year        40.0         7            4  
4   Just as welcome now as I felt last year         NaN        15            8  

[5 rows x 61 columns]

In [62]:
df = df[["Country", "EdLevel", "YearsCodePro", "Employment", "ConvertedComp"]]
df = df.rename({"ConvertedComp": "Salary"}, axis = 1)
df.head()

Country                                          EdLevel  \
0             Germany  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
1      United Kingdom     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2  Russian Federation                                              NaN   
3             Albania  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
4       United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

  YearsCodePro                                         Employment  Salary  
0           27  Independent contractor, freelancer, or self-em...     NaN  
1            4                                 Employed full-time     NaN  
2          NaN                                                NaN     NaN  
3            4                                                NaN     NaN  
4            8                                 Employed full-time     NaN

In [63]:
df = df[df["Salary"].notnull()]
df.head()

Country                                            EdLevel  \
7    United States       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
9   United Kingdom    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
10  United Kingdom       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
11           Spain  Some college/university study without earning ...   
12     Netherlands  Secondary school (e.g. American high school, G...   

   YearsCodePro          Employment    Salary  
7            13  Employed full-time  116000.0  
9             4  Employed full-time   32315.0  
10            2  Employed full-time   40070.0  
11            7  Employed full-time   14268.0  
12           20  Employed full-time   38916.0

In [64]:
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34025 entries, 7 to 64154
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       34025 non-null  object 
 1   EdLevel       34025 non-null  object 
 2   YearsCodePro  34025 non-null  object 
 3   Employment    34025 non-null  object 
 4   Salary        34025 non-null  float64
dtypes: float64(1), object(4)
memory usage: 1.6+ MB


In [65]:
df = df[df["Employment"] == "Employed full-time"]


In [68]:
df = df.drop("Employment", axis = 1)

In [82]:
test = df["Country"].value_counts()

print(len(test))
test

154


United States     7569
India             2425
United Kingdom    2287
Germany           1903
Canada            1178
                  ... 
Benin                1
Fiji                 1
San Marino           1
Guinea               1
Andorra              1
Name: Country, Length: 154, dtype: int64

In [85]:
def remove_short_categories(categories,cutoff):
    categorie_map = {}
    for x in range(len(categories)):
        if categories.values[x] >= cutoff:
            categorie_map[categories.index[x]] = categories.index[x]
        else:
            categorie_map[categories.index[x]] = "Other"
    return categorie_map

In [86]:
country_map = remove_short_categories(df.Country.value_counts(),500)
df["Country"] = df["Country"].map(country_map)
df.Country.value_counts()

Other                 8549
United States         7569
India                 2425
United Kingdom        2287
Germany               1903
Canada                1178
Brazil                 991
France                 972
Spain                  670
Australia              659
Netherlands            654
Poland                 566
Italy                  560
Russian Federation     522
Sweden                 514
Name: Country, dtype: int64

In [90]:
df = df[df["Salary"] <= 280000]
df = df[df["Salary"] >= 20000]
df = df[df["Country"] != "Other"]


In [92]:
df.Country.value_counts()

United States         6864
United Kingdom        2003
Germany               1766
Canada                1100
France                 896
Netherlands            630
Australia              599
India                  588
Spain                  551
Sweden                 501
Italy                  457
Poland                 432
Brazil                 428
Russian Federation     339
Name: Country, dtype: int64

In [93]:
df["YearsCodePro"].unique()


array(['13', '4', '2', '20', '1', '3', '10', '12', '29', '6', '28', '8',
       '7', '23', '15', '25', '9', '11', 'Less than 1 year', '5', '21',
       '16', '18', '14', '32', '19', '22', '38', '30', '26', '27', '17',
       '24', '34', '35', '33', '36', '40', '39', 'More than 50 years',
       '31', '41', '45', '37', '42', '44', '43', '50', '49'], dtype=object)

In [95]:
def clean_exp(x):
    if x == "More than 50 years":
        return 50
    if x == "Less than 1 year":
        return 0.5
    return float(x)
df["YearsCodePro"] = df["YearsCodePro"].apply(clean_exp)
        

In [97]:
df["EdLevel"].unique()


array(['Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       'Associate degree (A.A., A.S., etc.)',
       'Professional degree (JD, MD, etc.)',
       'Some college/university study without earning a degree',
       'Other doctoral degree (Ph.D., Ed.D., etc.)',
       'I never completed any formal education',
       'Primary/elementary school'], dtype=object)

In [98]:
def cleanup_education(x):
    if "Bachelor’s degree" in x:
        return "Bachelor’s degree"
    if "Master’s degree" in x:
        return "Master’s degree"
    if "Professional degree" in x or "Other doctoral" in x:
        return "Post grad"
    return "Less than a Bachelors"
df["EdLevel"] = df["EdLevel"].apply(cleanup_education)

In [99]:
df["EdLevel"].unique()

array(['Bachelor’s degree', 'Master’s degree', 'Less than a Bachelors',
       'Post grad'], dtype=object)

In [100]:
df.head()

Country                EdLevel  YearsCodePro    Salary
7    United States      Bachelor’s degree          13.0  116000.0
9   United Kingdom        Master’s degree           4.0   32315.0
10  United Kingdom      Bachelor’s degree           2.0   40070.0
12     Netherlands  Less than a Bachelors          20.0   38916.0
13   United States  Less than a Bachelors           1.0   66000.0

In [101]:
from sklearn.preprocessing import LabelEncoder
le_education = LabelEncoder()
df["EdLevel"] = le_education.fit_transform(df["EdLevel"])
df["EdLevel"].unique()

array([0, 2, 1, 3])

In [102]:
le_country = LabelEncoder()
df["Country"] = le_country.fit_transform(df["Country"])
df["Country"].unique()

array([13, 12,  7,  4,  2,  6,  1,  3, 11,  5, 10,  8,  0,  9])

In [122]:
X = df.drop("Salary", axis=1)
y = df["Salary"]

In [123]:
from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(random_state=0)
dec_tree_reg.fit(X.values, y.values)

DecisionTreeRegressor(random_state=0)

In [127]:
import numpy as np
X = np.array([["United States", 'Master’s degree', 10 ]])
X

array([['United States', 'Master’s degree', '10']], dtype='<U15')

In [128]:
X[:, 0] = le_country.transform(X[:,0])
X[:, 1] = le_education.transform(X[:,1])
X = X.astype(float)
X

array([[13.,  2., 10.]])

In [129]:
y_prediction = dec_tree_reg.predict(X)
y_prediction

array([136887.62068966])

In [130]:
import pickle

In [131]:
data = {"model":dec_tree_reg, "le_country": le_country, "le_education":le_education}
with open('salary_model.pkl', "wb") as file:
    pickle.dump(data,file)